// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmU1PyHk17w2K6j4BX7FmHZvcPWIehFI',
    appId: '1:539233975819:web:ffd3e508331701ef40d10e',
    messagingSenderId: '539233975819',
    projectId: 'firstflutterapp-27ec2',
    authDomain: 'firstflutterapp-27ec2.firebaseapp.com',
    storageBucket: 'firstflutterapp-27ec2.firebasestorage.app',
    measurementId: 'G-MJWVKRSRZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCehs8Kt0Ndh3HQLZqVt7CwxnwbnDyXaE',
    appId: '1:539233975819:android:d0112491f0ba47c940d10e',
    messagingSenderId: '539233975819',
    projectId: 'firstflutterapp-27ec2',
    storageBucket: 'firstflutterapp-27ec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKDYkp2cMN9bJnNBsi0cS94BKmzDe0gfc',
    appId: '1:539233975819:ios:2f4987863e486a3e40d10e',
    messagingSenderId: '539233975819',
    projectId: 'firstflutterapp-27ec2',
    storageBucket: 'firstflutterapp-27ec2.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterApp',
  );

}